name: agent-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - h5py
  - hdf5plugin
  - pytables
  - black
  - pip
  - pip:
    - law
    - luigi
    - torch
    - torchvision
